### ISSUE TITLE
Cannot Properly parse aliased ]

### ISSUE THREAD

**Issue by tusooa** [z-shell/F-Sy-H#20]
aliased `$` is correctly parsed as an alias, but aliased `]` is parsed as "unexpected symbol."
![image](https://user-images.githubusercontent.com/299873/161368093-cfbc56e4-8b0e-405f-bc80-1de3ea661707.png)
the `]`s at the beginning of the line are my prompts.

**Comment by ss-o** [comment]
Hey @tusooa:wave:

Could you provide more details about the system and your `.zshrc` to reproduce the issue? :octocat: 

> e.g: echo "OSTYPE=${OSTYPE} CPUTYPE=$(uname -m) / MACHINE_TYPE=$MACHTYPE ZSH_VERSION=${ZSH_VERSION}"

**Comment by ss-o** [comment]
@tusooa, 

Additionally, now you can set up tests for any plugin.
Check https://github.com/z-shell/z-a-test.

**Comment by tusooa** [comment]
> Hey @tusooawave
> 
> Could you provide more details about the system and your `.zshrc` to reproduce the issue? :octocat:
> 
> > e.g: echo "OSTYPE=${OSTYPE} CPUTYPE=$(uname -m) / MACHINE_TYPE=$MACHTYPE ZSH_VERSION=${ZSH_VERSION}"

`OSTYPE=linux-gnu CPUTYPE=x86_64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.8.1`

https://lily.kazv.moe/tusooa/apps/-/blob/servant/Config/zshrc

**Comment by tusooa** [comment]
> > Hey @tusooawave
> > Could you provide more details about the system and your `.zshrc` to reproduce the issue? :octocat:
> > > e.g: echo "OSTYPE=${OSTYPE} CPUTYPE=$(uname -m) / MACHINE_TYPE=$MACHTYPE ZSH_VERSION=${ZSH_VERSION}"
> 
> `OSTYPE=linux-gnu CPUTYPE=x86_64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.8.1`
> 
> https://lily.kazv.moe/tusooa/apps/-/blob/servant/Config/zshrc

or rather, use a user without any zshrc and do the following

```
tusooa-yoga% cd
tusooa-yoga% . ./F-Sy-H/fast-syntax-highlighting.plugin.zsh
tusooa-yoga% alias ']'=''
tusooa-yoga% alias '$'=''
tusooa-yoga% ] ls
tusooa-yoga% $ ls
```

**Comment by ss-o** [comment]
[![asciicast](https://asciinema.org/a/485256.svg)](https://asciinema.org/a/485256)

**Comment by ss-o** [comment]
> https://github.com/z-shell/community/blob/main/docs/zi-asciinema/INSTALL.md
To share terminal recordings.

**Comment by ss-o** [comment]
### Option 1
Create a folder name: tusooa
Put your config and we will test it in the container. :octocat: :upside_down_face: 

https://github.com/z-shell/playground/

### Option 2
Or try your config in the ZI container:

docker run -it ghcr.io/z-shell/zd:latest
https://github.com/z-shell/zd/pkgs/container/zd/18549345?tag=latest

**Comment by ss-o** [comment]
Language barrier :octocat: :1st_place_medal: 
@Colerar, @prnake

**Comment by tusooa** [comment]
> ### Option 1
> 
> Create a folder name: tusooa Put your config and we will test it in the container. :octocat: upside_down_face
> 
> https://github.com/z-shell/playground/
> ### Option 2
> 
> Or try your config in the ZI container:
> 
> docker run -it ghcr.io/z-shell/zd:latest https://github.com/z-shell/zd/pkgs/container/zd/18549345?tag=latest

https://user-images.githubusercontent.com/299873/162502225-12261797-947b-4629-88e5-8e2cd7bb45e1.mp4

**Comment by ss-o** [comment]
Nope, not here https://github.com/z-shell/F-Sy-H/blob/3b654bbd3c973216c22878ac716595d6428f0d5c/fast-highlight#L295

Still have a few alternatives to check. so will update you on this. :ballot_box_with_check:

**Comment by ss-o** [comment]
@tusooa, it seems you are unable to alias `[` `]`, due to conflict with the bracket highlighter:
https://github.com/z-shell/F-Sy-H/blob/3b654bbd3c973216c22878ac716595d6428f0d5c/fast-highlight#L168

This should solve the issue:

```shell
export FAST_HIGHLIGHT[use_brackets]=0
```

**Comment by tusooa** [comment]
Ok.
