### ISSUE TITLE
[docs]: Installation instructions for antigen is incorrect

### ISSUE THREAD

**Issue by nesvand** [z-shell/F-Sy-H#29]
### Description

As per #22 `antigen` requires special flags to indicate the use of `main` as the primary branch.

Instructions should specify `antigen bundle z-shell/F-Sy-H --branch=main`

### Select the area that is associated with this issue.

ZI (this repository)

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

nesvand@gmail.com

**Comment by ss-o** [comment]
Thank you for your contribution! :octocat:
