### ISSUE TITLE
Deleted repo drama and zdharma-continuum

### ISSUE THREAD

**Issue by vimpostor** [z-shell/F-Sy-H#8]
I just saw that https://github.com/zdharma/fast-syntax-highlighting got created again and now points to this repo (https://github.com/z-shell/fast-syntax-highlighting) as upstream repo. Are you the real zdharma and is this now again the official upstream? https://github.com/zdharma-continuum/fast-syntax-highlighting got created in the meantime and accepted in the community.

If you are the real zdharma, can we rely on you not again deleting this repo?

More context for the drama: https://www.reddit.com/r/zsh/comments/qinb6j/httpsgithubcomzdharma_has_suddenly_disappeared_i/

I think it would be helpful for you to give us an answer on all this and not just pretend like it never happened.

**Comment by wicoop** [comment]
Not sure about dramas, but this is one of many forks: [search?q=fast-syntax-highlighting](https://github.com/search?l=Shell&o=desc&q=fast-syntax-highlighting&s=&type=Repositories). I assume it is most reasonable to use the one accepted in the community.

Hopefully, it solves the issue.

Sincerely,

**Comment by vimpostor** [comment]
Well it doesn't really answer my question since it was was more about whether this is now the official upstream repository of the original repo by @psprint since https://github.com/zdharma/fast-syntax-highlighting is listed as a fork of this repo.
From your answer I can't tell who is behind this repo. I guess to put it directly: Who owns the z-shell group and who owns the new https://github.com/zdharma group and are they the same person?

**Comment by ss-o** [comment]
Hey :wave:,

---

> Well it doesn't really answer my question since it was was more about whether this is now the official upstream repository of the original repo by @psprint since https://github.com/zdharma/fast-syntax-highlighting is listed as a fork of this.

No, this is not the official upstream repository. @psprint work is highly respected and he is always welcome to contact me to discuss anything that may concern him.

---

> I guess to put it directly: Who owns the z-shell group and who owns the new https://github.com/zdharma group and are they the same person?

I am the owner of [github.com/z-shell](https://github.com/z-shell). I do not own [github.com/zdharma](https://github.com/zdharma).

---

In my opinion, @psprint clearly stated that he does not want to participate and doesn't have to answer to anyone unless he wants.

The discussion on this issue and conceivably some additional activities - **indicates unwanted and/or repeated surveillance by an individual or group toward another person.  It will not be supported nor tolerated**.

Any further questions which may solve the issue or areas of concern are welcome any time. Hopefully, together we can maintain healthy communities :octocat:

All posts/messages should adhere to the community [**code of conduct**](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

@ss-o,
 Salvydas Lukosius,

**Comment by vimpostor** [comment]
Thanks for clearing this up, I guess this solves the issue for me.

 > The discussion on this issue and conceivably some additional activities - **indicates unwanted and/or repeated surveillance by an individual or group toward another person. It will not be supported nor tolerated**.
> 
> All posts/messages should adhere to the community [**code of conduct**](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

BTW I think it is unnecessary to mention the code of conduct in this discussion. At no point was this discussion uncivil. When someone deletes a very popular repository entirely and then suddenly the zdharma group is created again, it is natural to be curious about who is behind that account. It would be ridiculous to call this surveillance, especially since Github doesn't treat it lightly when someone actively sabotages millions of users (see the faker.js incident), and "deleting a repo entirely" clearly is part of that definition.
So I guess I don't understand why you are going for this defensive measure when I was just genuinely and politely asking out of curiosity.


Thanks again for clearing this up, I guess I will stick to the zdharma-continuum fork now.

Edit: Still it would be helpful to know who owns the https://github.com/zdharma space now. If it is just someone pretending to be the old zdharma, that is not only identity theft, they could push malicious code to million users who update their clone which still has that repo as upstream URL. Of course it could also just be the case, that a good person just wants to remove the 404 from that repo so that people can clone from the old URL again - in any case it would be helpful to know who is behind that group. That's not called surveillance, that's called being cautious.

**Comment by ss-o** [comment]
Thank you, this type of incident is not the first one. It's not always that easy. For me, it all seems the right thing to do. My apologies if I made you feel uncomfortable.

Your security concerns can be answered by mail: opsec@digitalclouds.pro.

Many thanks,

@ss-o,
Salvydas Lukosius.

**Comment by BachoSeven** [comment]
> I am the owner of [github.com/z-shell](https://github.com/z-shell). I do not own [github.com/zdharma](https://github.com/zdharma).

@ss-o how come is `z-shell.pages.dev` in the "About" section of [this](https://github.com/zdharma/zdharma.github.io) `zdharma` repo then?

![image](https://user-images.githubusercontent.com/55460785/153616998-2094ada6-47dd-4f88-92b3-06b55b560755.png)

**Comment by bradenmitchell** [comment]
> @ss-o how come is `z-shell.pages.dev` in the "About" section of [this](https://github.com/zdharma/zdharma.github.io) `zdharma` repo then?

Not only that, but the repo for zdharma/fast-syntax-highlighting lists z.digitalclouds.dev in its about section which is conveniently similar to the email address provided by @ss-o above 

> Your security concerns can be answered by mail: [opsec@digitalclouds.pro](mailto:opsec@digitalclouds.pro).

Seems pretty sus to me

<img width="1422" alt="Screen Shot 2022-02-23 at 6 14 21 pm" src="https://user-images.githubusercontent.com/32005299/155278985-a659a350-791c-4f56-9f7d-059b88333753.png">

**Comment by pskarma** [comment]
@BachoSeven

> > I am the owner of [github.com/z-shell](https://github.com/z-shell). I do not own [github.com/zdharma](https://github.com/zdharma).
> 
> @ss-o how come is `z-shell.pages.dev` in the "About" section of [this](https://github.com/zdharma/zdharma.github.io) `zdharma` repo then?
> 
> ![image](https://user-images.githubusercontent.com/55460785/153616998-2094ada6-47dd-4f88-92b3-06b55b560755.png)

"How come?" What kind of question is this? Could please ask a full/correct question?

**Comment by pskarma** [comment]
@bradenmitchell,

> > @ss-o how come is `z-shell.pages.dev` in the "About" section of [this](https://github.com/zdharma/zdharma.github.io) `zdharma` repo then?
> 
> Not only that, but the repo for zdharma/fast-syntax-highlighting lists z.digitalclouds.dev in its about section which is conveniently similar to the email address provided by @ss-o above
> 
> > Your security concerns can be answered by mail: [opsec@digitalclouds.pro](mailto:opsec@digitalclouds.pro).
> 
> Seems pretty sus to me
> 
> <img alt="Screen Shot 2022-02-23 at 6 14 21 pm" width="1422" src="https://user-images.githubusercontent.com/32005299/155278985-a659a350-791c-4f56-9f7d-059b88333753.png">

Not sure what is sus, how it is related at all. Or are you just having some kind of fun? :eyes:
